# GitHub Secret Scanning Configuration
# https://docs.github.com/en/code-security/secret-scanning/defining-custom-patterns-for-secret-scanning

# Paths to exclude from secret scanning push protection
paths-ignore:
  - 'SecureTaskApi/Config/DatabaseConfig.cs'  # Contains intentional test secrets
  - '.env.example'                             # Contains intentional test secrets
  - 'SECURITY_SCANNING.md'                     # Documentation may reference secrets
  - 'GITLEAKS_QUICKSTART.md'                   # Documentation may reference secrets
  - '**/test/**/*.cs'                          # Test files may contain mock secrets
  - '**/tests/**/*.cs'                         # Test files may contain mock secrets
